version: '3'
services:
  # Node backend
  backend:
    build: .
    image: invoice-manager-backend
    environment:
      MONGODB_URI: mongodb://root:example@mongo
    depends_on:
      - mongo
    ports:
      - 3000:3000

  # MongoDB database
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    
  # Mongo Express for managing the database
  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
    # environment:
    #   ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #   ME_CONFIG_MONGODB_ADMINPASSWORD: example